# ░█████╗░██████╗░██╗░░░██╗░█████╗░███╗░░██╗░█████╗░███████╗██████╗░███████╗██╗░░░░░██╗░░░██╗████████╗██████╗░░█████╗░░██████╗
# ██╔══██╗██╔══██╗██║░░░██║██╔══██╗████╗░██║██╔══██╗██╔════╝██╔══██╗██╔════╝██║░░░░░╚██╗░██╔╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝
# ███████║██║░░██║╚██╗░██╔╝███████║██╔██╗██║██║░░╚═╝█████╗░░██║░░██║█████╗░░██║░░░░░░╚████╔╝░░░░██║░░░██████╔╝███████║╚█████╗░
# ██╔══██║██║░░██║░╚████╔╝░██╔══██║██║╚████║██║░░██╗██╔══╝░░██║░░██║██╔══╝░░██║░░░░░░░╚██╔╝░░░░░██║░░░██╔══██╗██╔══██║░╚═══██╗
# ██║░░██║██████╔╝░░╚██╔╝░░██║░░██║██║░╚███║╚█████╔╝███████╗██████╔╝███████╗███████╗░░░██║░░░░░░██║░░░██║░░██║██║░░██║██████╔╝
# ╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚══╝░╚════╝░╚══════╝╚═════╝░╚══════╝╚══════╝░░░╚═╝░░░░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░

MySQL:
  username:
  password:
  database:
  port:
  host:
